FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIPER_VOICE_DIR=/opt/voxlyra-voices
ENV VOSK_MODEL_PATH=/app/storage/tts/models/vosk
ENV TTS_VOSK_MODEL_DIR=/app/storage/tts/models/vosk
ENV TTS_VOSK_MODEL_NAME=vosk-model-tts-ru-0.9-multi

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates libarchive13 fonts-dejavu-core tesseract-ocr tesseract-ocr-rus tesseract-ocr-eng \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN set -eux; \
    pip install --no-cache-dir -r requirements.txt; \
    mkdir -p "$PIPER_VOICE_DIR"; \
    success=0; \
    for attempt in 1 2 3; do \
      if python -m piper.download_voices \
        --download-dir "$PIPER_VOICE_DIR" \
        ru_RU-irina-medium ru_RU-dmitri-medium; then \
        success=1; \
        break; \
      fi; \
      sleep 5; \
    done; \
    test "$success" = "1"; \
    test -s "$PIPER_VOICE_DIR/ru_RU-irina-medium.onnx"; \
    test -s "$PIPER_VOICE_DIR/ru_RU-irina-medium.onnx.json"; \
    test -s "$PIPER_VOICE_DIR/ru_RU-dmitri-medium.onnx"; \
    test -s "$PIPER_VOICE_DIR/ru_RU-dmitri-medium.onnx.json"

COPY . .

# Reject syntax-broken images during docker build instead of discovering the
# problem only after deployment. Remove generated bytecode from the final layer.
RUN python -m compileall -q app scripts main.py \
    && find app scripts -type d -name '__pycache__' -prune -exec rm -rf {} + \
    && find app scripts -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete

EXPOSE 3000

# Liveness remains available while heavy migrations are running, but switches to
# failure after a terminal bootstrap error. Strict readiness is exposed separately
# at /readiness and /readyz for deployment systems that support it.
HEALTHCHECK --interval=30s --timeout=5s --start-period=90s --retries=3 \
    CMD python scripts/healthcheck.py --path /health --timeout 3 --quiet || exit 1

RUN mkdir -p data data/profile_avatars storage/covers storage/books storage/audio storage/tts storage/tts/models/vosk storage/comics storage/temp storage/legal \
    && chmod +x scripts/start.sh

CMD ["sh", "scripts/start.sh"]
